# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetalcloudCli < Formula
  desc "Metalcloud's CLI"
  homepage "https://metalsoft.io/"
  version "7.0.7"

  on_macos do
    on_intel do
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.7/metalcloud-cli_7.0.7_Darwin_x86_64.tar.gz"
      sha256 "3141be2f7c82948e8b1f3eae333f6e917f2c16f386ee4beb990442cf5592c1fe"

      def install
        bin.install "metalcloud-cli"
      end
    end
    on_arm do
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.7/metalcloud-cli_7.0.7_Darwin_arm64.tar.gz"
      sha256 "7d8537fc056d2fdfe97fb53ea08e8dceadab2dcdc3ff25452d3be02c1df00888"

      def install
        bin.install "metalcloud-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.7/metalcloud-cli_7.0.7_Linux_x86_64.tar.gz"
        sha256 "e694937fcc439308e55a8995c4d0455fa4cd76fecd24f4624923c358b29d38ff"

        def install
          bin.install "metalcloud-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.7/metalcloud-cli_7.0.7_Linux_arm64.tar.gz"
        sha256 "023109b733f8ec0a2f363254b653426dd007f8cda1fe85c7fce25528800d9843"

        def install
          bin.install "metalcloud-cli"
        end
      end
    end
  end

  def caveats
    <<~EOS
      metalcloud-cli help
    EOS
  end
end
