# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetalcloudCli < Formula
  desc "Metalcloud's CLI"
  homepage "https://metalsoft.io/"
  version "7.0.8"

  on_macos do
    on_intel do
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.8/metalcloud-cli_7.0.8_Darwin_x86_64.tar.gz"
      sha256 "69eb31b052af2b39481aa26153de22b8d9a8594c268f1096b77aea669f320fa6"

      def install
        bin.install "metalcloud-cli"
      end
    end
    on_arm do
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.8/metalcloud-cli_7.0.8_Darwin_arm64.tar.gz"
      sha256 "7228fbf2756045593de9749375fbc2d9490a2eb7bb6e9de9457e702224dae4d1"

      def install
        bin.install "metalcloud-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.8/metalcloud-cli_7.0.8_Linux_x86_64.tar.gz"
        sha256 "9b98f0d829a92c70ce2f0975855a48c7a1cd066b30517edac83b4c3572155b68"

        def install
          bin.install "metalcloud-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v7.0.8/metalcloud-cli_7.0.8_Linux_arm64.tar.gz"
        sha256 "83175144164a2e61cefd21b49cd3a4147caa60d62c85a5b0562e64caa77dd0d6"

        def install
          bin.install "metalcloud-cli"
        end
      end
    end
  end

  def caveats
    <<~EOS
      metalcloud-cli help
    EOS
  end
end
