# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetalcloudCli < Formula
  desc "Metalcloud's CLI"
  homepage "https://metalsoft.io/"
  version "2.8.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v2.8.7/metalcloud-cli_2.8.7_Darwin_x86_64.tar.gz"
      sha256 "cca804e9aedb2dd74cedc7dc568dd105afcd9db83d99498b03456716122f8a4f"

      def install
        bin.install "metalcloud-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v2.8.7/metalcloud-cli_2.8.7_Darwin_arm64.tar.gz"
      sha256 "00f08aaaaf0c0b2629f42df84ae1ebf0681d74a7332b342533a87ed45d1e7b33"

      def install
        bin.install "metalcloud-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v2.8.7/metalcloud-cli_2.8.7_Linux_arm64.tar.gz"
      sha256 "ecb0dcf2ef106ea117c7b771b983dcafee95b3f44fac50a38b22d24a2ef856ac"

      def install
        bin.install "metalcloud-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v2.8.7/metalcloud-cli_2.8.7_Linux_x86_64.tar.gz"
      sha256 "fc78252f920763d639f893f4d1a6adbf3df819689b6bea39dc517b01271f9538"

      def install
        bin.install "metalcloud-cli"
      end
    end
  end

  def caveats; <<~EOS
    metalcloud-cli help
  EOS
  end
end
