# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetalcloudCli < Formula
  desc "Metalcloud's CLI"
  homepage "https://metalsoft.io/"
  version "3.2.14"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v3.2.14/metalcloud-cli_3.2.14_Darwin_arm64.tar.gz"
      sha256 "c820f50e51c4e2cbd272060a642a1f86828f863efd413d143d70e725052e8325"

      def install
        bin.install "metalcloud-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v3.2.14/metalcloud-cli_3.2.14_Darwin_x86_64.tar.gz"
      sha256 "0ba62dd98373f4b61b87074f6b0efe8427a55a2bc9f0f44e812594fa5151c444"

      def install
        bin.install "metalcloud-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v3.2.14/metalcloud-cli_3.2.14_Linux_arm64.tar.gz"
      sha256 "4dad368f59b54421a6b86650d3d5a8b9a02f4d8d9ef15b82adea400715a44a1c"

      def install
        bin.install "metalcloud-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metalsoft-io/metalcloud-cli/releases/download/v3.2.14/metalcloud-cli_3.2.14_Linux_x86_64.tar.gz"
      sha256 "e26e7b707cdb79d84675a9a9d05b579e2c285ebf862954b6f078506d376d6ce1"

      def install
        bin.install "metalcloud-cli"
      end
    end
  end

  def caveats
    <<~EOS
      metalcloud-cli help
    EOS
  end
end
